In [3]:
import numpy as np
a=np.array((2,4,6))
print(a)

[2 4 6]


In [4]:
a=np.array([[1,2,3],[4,5,7]])
print(a)

[[1 2 3]
 [4 5 7]]


In [16]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[6,5,4]])
np.add(a,b)

array([[ 4,  6,  8],
       [10, 10, 10]])

In [17]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[6,5,4]])
np.multiply(a,b)

array([[ 3,  8, 15],
       [24, 25, 24]])

In [18]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[6,5,4]])
np.divide(a,b)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 1.        , 1.5       ]])

In [19]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[6,5,4]])
np.subtract(a,b)

array([[-2, -2, -2],
       [-2,  0,  2]])