In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris

In [13]:
x,y=load_iris(return_X_y=True)

In [16]:
pd.DataFrame(x)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [19]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.40)

In [21]:
classifier=GaussianNB()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [22]:
result=confusion_matrix(y_test,y_pred)
print("confusion_matrix")
print(result)

confusion_matrix
[[18  0  0]
 [ 0 23  1]
 [ 0  2 16]]


In [23]:
result2=classification_report(y_test,y_pred)
print("classification_report")
print(result2)

classification_report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.92      0.96      0.94        24
           2       0.94      0.89      0.91        18

    accuracy                           0.95        60
   macro avg       0.95      0.95      0.95        60
weighted avg       0.95      0.95      0.95        60



In [24]:
result3=accuracy_score(y_test,y_pred)
print("accuracy")
print(result3)

accuracy
0.95
